repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: debug-statements
    - id: check-ast
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
    - id: pyupgrade
      args: ['--py37-plus']
      exclude: _version.py|versioneer.py
