name: build docs

on:
  push:
    branches:
      - 'master'
      - 'release/*'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    env:
      DISPLAY: ':99.0'

    steps:
    - uses: actions/checkout@v2
    - name: setup ubuntu-latest xvfb
      uses: ./.github/actions/setup-ubuntu-latest-xvfb
    - name: install pandoc ubuntu
      run: sudo apt install pandoc
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: prepare pip cache
      id: prepare-cache-pip
      uses: ./.github/actions/prepare-cache-pip
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.prepare-cache-pip.outputs.cache-dir }}
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/docs_requirements.txt') }}-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-pip-

    - name: install requirements.txt
      run: |
        pip install -r requirements.txt
    - name: install docs_requirements.txt
      run: |
        pip install -r docs_requirements.txt
    - name: install qcodes
      run: pip install .
    - name: Build docs
      run: |
        cd docs
        export SPHINXOPTS="-W -v"
        make html
    - name: Upload build docs
      uses: actions/upload-artifact@v2
      with:
        name: docs_${{ matrix.python-version }}
        path: ${{ github.workspace }}/docs/_build/html
